# Generated by Django 3.0.6 on 2020-05-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_instructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='cohort_id',
            new_name='cohort',
        ),
    ]
