# Generated by Django 3.0.5 on 2020-05-07 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0006_auto_20200507_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.Cohort'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='slack_handle',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='specialty',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
